allowBuilds:
  esbuild: true
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@jbrowse/mobx-state-tree@6.0.0 || 6.2.0 || 6.3.0'
  - '@gmod/gbz-base@1.1.0 || 2.1.0 || 2.3.0 || 2.5.0 || 2.6.0 || 2.6.2 || 2.6.3 || 2.6.4 || 2.6.5 || 2.8.0 || 3.0.0 || 4.0.0 || 4.1.0 || 5.0.0 || 6.0.1 || 7.0.0'
  - '@gmod/tubemap-core@0.1.0'
  - '@gmod/tabix@3.9.0'
  - '@jbrowse/bandage-core@6.0.2 || 6.0.3 || 6.0.4 || 6.1.0 || 6.1.1 || 7.0.0 || 7.1.0'
